---
  - name: Install DNS server
    yum:
      name: "{{dns_pkg}}"
      state: latest

  - name: Copy named config file
    template:
      src: files/named.conf.j2
      dest: /etc/named.conf

  - name: Copy DNS forward query file
    template:
      src: files/forward.lubs.j2
      dest: /var/named/forward.lubs

  - name: Copy DNS reverse query file
    template:
      src: files/reverse.lubs.j2
      dest: /var/named/reverse.lubs

  - name: Restart named services
    service:
      name: "{{dns_service}}"
      state: restarted

...
